### PR TITLE
Update cookie-getter dependency

### PR DESCRIPTION
**Pull request by mhamann**

### CODE REVIEW

**Comment by mhamann** [comment]
@HenrikJoreteg can you give me contributor access to the npm package? I'm ready to push an update.

**Comment by HenrikJoreteg** [comment]
oh, I forgot, sorry. Done!

**Comment by HenrikJoreteg** [comment]
Thanks for doing this! Nice work!

**Comment by HenrikJoreteg** [comment]
By the way, you should add yourself to the readme as maintainer :)

**Pull request merged**
